# Generated by Django 3.1.3 on 2022-03-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_url',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
