# Generated by Django 3.1.3 on 2022-03-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='', path='C:\\Users\\03751260\\OneDrive - Mango\\Documentos\\Innovacion\\PoC\\Apps\\Django_demo\\Portfolio-website-django\\myportfolio/static/img'),
        ),
    ]
